---
host: 127.0.0.1
base_port: 9000
social_graph:
  nodes:
    - name: p0
      positively_tested: true
    - name: p1
      positively_tested: false
    - name: p2
      positively_tested: false
  node_holes: []
  edge_property: directed
  edges:
    - - 0
      - 1
      - encounters:
          - timestamp: "2021-02-04T15:44:00Z"
            intensity: HighRisk
          - timestamp: "2021-02-04T14:44:00Z"
            intensity: LowRisk
    - - 1
      - 2
      - encounters:
          - timestamp: "2021-02-04T15:44:00Z"
            intensity: HighRisk
          - timestamp: "2021-02-04T13:44:00Z"
            intensity: LowRisk
