[package]
name = "runner"
version = "0.1.0"
authors = ["Leo <lstwn@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
signal-hook = "0.3.7"
anyhow = "1.0.38"
crossbeam = "0.8.0"
